name: Print World

on: 
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World From GitHub Actions"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome Message
        run: echo "Welcome to GitHub Actions"
  
